version: '2'

services:
  verdaccio:
    container_name: npm-registry
    build: ./image
    extra_hosts:
      - "dc01.devops.lab:10.0.0.105"
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
volumes:
  verdaccio:
    driver: local
